---
title: "Model Setup"
output: html_document
date: "2025-01-10"
---
## Library Loading
```{r setup, include=FALSE}
options(packrat.dependency.discovery.renv = TRUE)
require(ggplot2)
require(ggthemes)
require(plyr)
require(stargazer)
require(RColorBrewer)
require(scales)
require(gtable)
require(gridExtra)
require(data.table)
require(dplyr)
require(ggplot2)
require(readr)
require(tidyr)
require(lme4)
require(MASS)
library(daewr)
library(MASS)
library(GAD)
library(dplyr)
library(sjPlot)
library(blmeco)
```

```{r}
library(stringr)
dswithrepAbbECM <- dswithrep %>% mutate(across('Abb_ECMs', str_replace, ':|: ', ''))
```

## 3DP Analysis 
### Proliferation Model
```{r}
dswithrepAbbECM$CollagenI <- relevel(factor(dswithrepAbbECM$CollagenI, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$CollagenIV <- relevel(factor(dswithrepAbbECM$CollagenIV, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$Hyaluronic_Acid <- relevel(factor(dswithrepAbbECM$Hyaluronic_Acid, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$TenascinC <- relevel(factor(dswithrepAbbECM$TenascinC, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$Laminin <- relevel(factor(dswithrepAbbECM$Laminin, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$Fibronectin <- relevel(factor(dswithrepAbbECM$Fibronectin, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$Galectin3 <- relevel(factor(dswithrepAbbECM$Galectin3, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$Osteopontin <- relevel(factor(dswithrepAbbECM$Osteopontin, levels = c(0,0.25,0.5,0.75,1)), ref = 5)
dswithrepAbbECM$Decorin <- relevel(factor(dswithrepAbbECM$Decorin, levels = c(0,0.25,0.5,0.75,1)), ref = 5)

EdUmodel <- glmer(round(Mean_Percent_Positive) ~ 
                 (1|(Metadata_Stiffness:Metadata_Treatment):Metadata_Experiment:Metadata_Block:Replicate) +
                Metadata_Stiffness+ Metadata_Treatment + CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin + Abb_ECMs +
                 Metadata_Stiffness:Metadata_Treatment + Metadata_Stiffness:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin)+ Metadata_Stiffness:Abb_ECMs +  Metadata_Treatment:Abb_ECMs + Metadata_Treatment:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin) + Abb_ECMs:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin) + Metadata_Stiffness:Metadata_Treatment:Abb_ECMs + Metadata_Stiffness:Metadata_Treatment:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin)+
                 Metadata_Stiffness:Abb_ECMs:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin) + Metadata_Treatment:Abb_ECMs:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin), dswithrepAbbECM, 
               family = "poisson")

dispersion_glmer(EdUmodel)
anova(EdUmodel)
```

### Attachment Model 
```{r}
NewCombo <- dswithrepAbbECM %>% mutate(rounded_mean_object_counts = round(Mean_Nuclei))

simple.model <- glmer(rounded_mean_object_counts ~
                 (1|Metadata_Stiffness:Metadata_Experiment:Metadata_Block:Replicate) +
                 Metadata_Stiffness + Metadata_Treatment + CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin + Abb_ECMs,
               NewCombo, family = "poisson")

dispersion_glmer(simple.model)
anova(simple.model)
# #tab_model(simple.model)

surmodel <- glmer(round(Mean_Nuclei) ~ 
                 (1|(Metadata_Stiffness:Metadata_Treatment):Metadata_Experiment:Metadata_Block:Replicate) +
                Metadata_Stiffness+ Metadata_Treatment + CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin + Abb_ECMs +
                 Metadata_Stiffness:Metadata_Treatment + Metadata_Stiffness:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin)+ Metadata_Stiffness:Abb_ECMs + Metadata_Treatment:Abb_ECMs + Metadata_Treatment:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin) + Abb_ECMs:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin) + Metadata_Stiffness:Metadata_Treatment:Abb_ECMs + Metadata_Stiffness:Metadata_Treatment:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin)+
                Metadata_Stiffness:Abb_ECMs:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin) + Metadata_Treatment:Abb_ECMs:(CollagenI + CollagenIV + Hyaluronic_Acid + TenascinC + Laminin + Fibronectin + Galectin3 + Osteopontin + Decorin), NewCombo, 
               family = "poisson")

dispersion_glmer(surmodel)
anova(surmodel)
```

## Day 0 and Day 2 Adhesion
```{r}

```

